### PR TITLE
#45 Fix Host header on forwarded requests

### LINKED ISSUE #45: Host header is not rewritten
I am finding that Charon is forwarding my requests to the remote server with a `Host` header holding the old value (i.e. the host name of my local server). This is causing my requests to fail.

Is this a known issue? 

I will attempt to isolate and create a PR in the next day or two, unless this is my mistake somehow?

My Spring config looks like this:

```
charon.mappings[0].name: wordpress
charon.mappings[0].path: /wp-content
charon.mappings[0].destinations: https://example.com/wp-content
charon.mappings[0].timeout.read: 10000
```

### PR DESCRIPTION
**Pull request by RichardBradley**
This fixes #45 

The test "`def "Should proxy HTTPS request"()`" demonstrates that this fix works -- previously TLS requests that were being forwarded to https://github.com had a `Host` header of `localhost`, and were being rejected by GitHub's server. Now the request is succeeding.

### CODE REVIEW

File: src/main/java/com/github/mkopylec/charon/core/http/RequestForwarder.java [hunk 1]
```diff
@@ -76,11 +78,38 @@ public RequestForwarder(
...
+    /**
+     * Remove any protocol-level headers from the remote server's response that
+     * do not apply to the new response we are sending.
+     */
+    private void prepareForwardedResponseHeaders(ResponseData response) {
+        HttpHeaders headers = new HttpHeaders();
+        headers.putAll(response.getHeaders());
+        response.setHeaders(headers);
+
+        headers.remove("Transfer-Encoding");
```
Comment (RichardBradley) [inline src/main/java/com/github/mkopylec/charon/core/http/RequestForwarder.java]: Remote servers which use `Chunked` transfer encoding would fail to proxy correctly because line 85 causes Spring to buffer the remote body into a single entity, but we were previously passing over the remote `Transfer-Encoding: Chunked` header, confusing clients.

This fixes that issue. I have tested against a remote server with Chunked encoding, it works after this change but did not work before this change.

I have not added a unit test for this fix.

File: src/test/groovy/com/github/mkopylec/charon/specification/ProxyingRequestSpec.groovy [hunk 2]
```diff
@@ -145,6 +145,7 @@ abstract class ProxyingRequestSpec extends BasicSpec {
 
         then:
         assertThat(response)
-                .hasStatus(MOVED_PERMANENTLY)
+                .hasStatus(OK)
+                .bodyContains("<link rel=\"canonical\" href=\"https://github.com/\"")
```
Comment (RichardBradley) [inline src/test/groovy/com/github/mkopylec/charon/specification/ProxyingRequestSpec.groovy]: See comment in the body of this PR -- the test was actually failing before, i.e. the old assertion was wrong.
After fixing the `Host` header issue, the request now works, so I have fixed the assertion.
